### ISSUE TITLE
api.eia_backill KeyError: 'period'

### ISSUE THREAD

**Issue by neilmartindev** [LinkedInLearning/data-pipeline-automation-with-github-actions-4503382#23]
## Issue Overview
I get a KeyError in cell 60 when trying to create df3 from api.eia_backfill function in Py_eia_api.pynb.

## Describe your environment
MAC M1 using VSCode, Git to clone the Repo and using the Dev Container and Venv LINKEDIN_LEARNING. I've not made any changes to the code, just tried to run it alongside your course and got stuck on this cell. Yours seems to work flawlessly so not sure what's going on here.

## Steps to Reproduce
1. I cloned the Repo
2. Ran all cells in Py_eria_api.ipynb
3. Code block under "Handling A Large Data Request errors with KeyError

## Expected Behavior
Expected the cell to run and backfill with historic data

## Current Behavior

Errors withKeyError: 'period', it looks like it's trying to 

## Screenshots / Video

![Screenshot 2024-09-12 at 13 51 11](https://github.com/user-attachments/assets/a11e8aae-0031-425a-8dc6-50262a914e5c)
![Screenshot 2024-09-12 at 13 54 59](https://github.com/user-attachments/assets/b266eb5a-2fc6-4799-93c4-fae2b8894c2a)

**Comment by RamiKrispin** [comment]
Hi @neilmartindev 

I noticed this week that data before 2019 is no longer available, and that might cause the issue. Could you please try changing the start argument to `(2019,1,1,1)` and rerun the code?

**Comment by neilmartindev** [comment]
Worked a treat thank you!

**Comment by RamiKrispin** [comment]
Awesome!
